### ISSUE TITLE
Have all the packages in the same tree

### ISSUE THREAD

**Issue by ionelmc** [schlamar/pytest-cov#39]
A thing that really bugs me is that I can't `pip install https://github.com/schlamar/pytest-cov/archive/2.0.zip`. This is quite inconvenient for development where I have to use requirement files (most always).

Having that in mind having two repos for the whole shebang wasn't that bad ....

What do you think about this?

**Comment by schlamar** [comment]
You can install from subdirectories in pip's "editable" mode. See example 5 on https://pip.pypa.io/en/latest/reference/pip_install.html#examples

**Comment by ionelmc** [comment]
You're right
