### ISSUE TITLE
coverage.misc.CoverageException: No data to report.

### ISSUE THREAD

**Issue by ssbarnea** [schlamar/pytest-cov#42]
I think that this problem was also reported by others, like on http://stackoverflow.com/questions/18573542/coverage-py-does-not-cover-script-if-py-test-executes-it-from-another-directory

Please take a look at https://github.com/pycontribs/jira -- running it with "python setup.py test" will also use coverage but it seems that the coverage data is not properly stored or retried. 

It is quite confusing because when I run coveralls after running the tests, I do get a report, but when I try to export the coverage data I get the "No data to report" exception. You do not have to run it on your machine as you can also see the results on Travis CI.

I hope you can help me solve this issue, as having coverage integrated with pytest is something really useful. I do need to generate a coverage.xml file so I can use it in PyCharm IDE.

**Comment by schlamar** [comment]
Everything looks fine for me on the Travis CI logs, please elaborate and link directly to a Travis log where I can see this issue.

**Comment by ssbarnea** [comment]
Sorry, it seems that I solved the problem myself. It was working indeed so I close this.

Now my only remaining question is how to deal with the big amount of dead code (usually documentation lines) that appears as not covered in PyCharm. Is strange because on Coveralls this code does appear correctly, as skipped but on PyCharm it does appear as not-covered, making much harder to identify that real not-covered one.

Now I have to find out if the problem is inside the generated coverage.xml or is a bug of PyCharm.

Thank you.
