### ISSUE TITLE
function declarations and comments are not marked as covered

### ISSUE THREAD

**Issue by ssbarnea** [schlamar/pytest-cov#43]
Initially I assumed that is a bug in Coveralls but it seems that I managed to discover a strange bug which makes coverage tool to improperly mark functions or comments as not covered.

Please take a look at http://stackoverflow.com/questions/28024496/why-coveralls-does-report-the-function-or-methods-as-not-covered-when-body-is-co?noredirect=1#comment44434661_28024496 and https://coveralls.io/files/431523503#L433

The project is tested from Travis CI and the coverage parameters are loaded at runtime, see https://github.com/pycontribs/jira/blob/master/setup.py#L47

So to run it with coverage you only have to do: `python setup.py test`

Why is does behave like this and how to solve the problem? Thanks.

**Comment by schlamar** [comment]
This is a usage error. You import from "jira" in setup.py before pytest-cov and therefore coverage measurement is active...

**Comment by ssbarnea** [comment]
Thank you, I will try different patterns for avoiding this. The main reason is that need to "import" the version in setup.py, this is the only thing i need from inside the module.

/sorin

**Comment by schlamar** [comment]
You can use something like this https://github.com/shazow/urllib3/blob/master/setup.py#L15

Or run tests outside of setup.py.
