### ISSUE TITLE
multiprocessing failure

### ISSUE THREAD

**Issue by nijotz** [schlamar/pytest-cov#44]
The multiprocessing test here:

https://github.com/schlamar/pytest-cov/blob/f609c0609158db16b5acbdbeb7c5701bdc58fa18/pytest-cov/test_pytest_cov.py#L84

makes an assumption that any multiprocessing being used will start and end with the parent.  However, this is not the case in, for example, flask-testing.

https://github.com/jarus/flask-testing/blob/master/flask_testing/utils.py#L353

In the LiveServerTestCase, it uses multiprocessing.Process to run the server in the background and the user is given the main process to run Selenium tests.  The flask server is stopped and started for every test.  This is probably unnecessary, but regardless, a new server is started multiple times during testing, this results in multiple calls to the multiprocessing hook here:

https://github.com/schlamar/pytest-cov/blob/f609c0609158db16b5acbdbeb7c5701bdc58fa18/cov-core/cov_core.py#L12

which then calls cov_core_init.init() which subsequently calls cov.erase():

https://github.com/schlamar/pytest-cov/blob/f609c0609158db16b5acbdbeb7c5701bdc58fa18/cov-core/cov_core_init.py#L52

which destroys coverage data mid-test.

So, if I start and stop multiple background processes during tests, cov_core erases all that coverage data, and I don't have an easy way of making it stop.  I would prefer to run my tests with the `parallel = True` option set in .coveragerc, *not* have my coverage data erased when a forked process ends, run `coverage combine` manually and also run `coverage erase` manually.

**Comment by nijotz** [comment]
Hmm, I may be mistaken in whether the cov.erase() call is actually clearing existing coverage data.  Let me look into it some more.

**Comment by nijotz** [comment]
Ya, it looks like the coverage data was being generated in the first place due to flask-testing terminating the process uncleanly.

**Comment by nijotz** [comment]
https://github.com/jarus/flask-testing/issues/70

**Comment by schlamar** [comment]
cov_core_init creates a unique data file for the current process (due to `data_suffix=True`). So a `cov.erase` should have no effect at that point (not sure why it's even there, this is legacy code). As you have already noticed, coverage data is missing because the server process is not exited cleanly.
