### ISSUE TITLE
Adding the nose --cover-min-percentage=100 option

### ISSUE THREAD

**Issue by Natim** [schlamar/pytest-cov#56]
We try to switch from nose to pytest on our projects (thanks to @magopian)

One of the missing feature we have is to fail if the coverage is not 100%.
http://nose.readthedocs.org/en/latest/usage.html#cmdoption--cover-min-percentage

Do you know a pluggin that can allow us to do that?

**Comment by Natim** [comment]
Actually it is the ``--fail-under`` option for coverage.

**Comment by Natim** [comment]
https://github.com/schlamar/pytest-cov/blob/2.0/pytest-cov/pytest_cov.py#L41-L42

And it is the ``--cov-min`` for pytest-cov

**Comment by Natim** [comment]
py.test: error: unrecognized arguments: --cov-min=100

**Comment by ionelmc** [comment]
@Natim Meanwhile, you could use [pytest-cover](https://pypi.python.org/pypi/pytest-cover) (option available as `--cov-fail-under`). It's a provisional fork.

**Comment by Natim** [comment]
Thanks @ionelmc this is really useful :)

**Comment by tevren** [comment]
For anyone else who stumbles to onto this, `--cov-fail-under` is now included in the main branch.
