### ISSUE TITLE
Race condition in test_dist_combine_racecondition

### ISSUE THREAD

**Issue by schlamar** [schlamar/pytest-cov#64]
@ionelmc Looks like your `test_dist_combine_racecondition` has a race condition: https://travis-ci.org/schlamar/pytest-cov/jobs/70355353

**Comment by ionelmc** [comment]
Odd ... will look into it


Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by schlamar** [comment]
@ionelmc Any update here? I really would like to have this resolved before a 2.0 release.

**Comment by schlamar** [comment]
Again: https://travis-ci.org/schlamar/pytest-cov/jobs/70962140

**Comment by schlamar** [comment]
I've run this locally for a while and it never failed. Might be a Travis issue...

**Comment by schlamar** [comment]
I've tried with this:

    while true; do sleep 1; tox -e 2.7 -- -k test_dist_combine_racecondition -v; test $? -gt 0 && break; done

**Comment by schlamar** [comment]
Now it failed, too...
