### ISSUE TITLE
Race condition in test_dist_subprocess_not_collocated

### ISSUE THREAD

**Issue by schlamar** [schlamar/pytest-cov#69]
- https://ci.appveyor.com/project/schlamar/pytest-cov/build/master-34/job/eahd3sy63fvjsdaa
- https://ci.appveyor.com/project/schlamar/pytest-cov/build/looponfail-29/job/a8dm1qbpjewo01i3

Probably a regression from #63

cc @ionelmc

**Comment by ionelmc** [comment]
I suspect the cause is pids being reused. @schlamar did we have custom file naming before?

**Comment by schlamar** [comment]
Might be fixed with  #71

**Comment by ionelmc** [comment]
Interesting. Just for my curiosity: why doesn't previous coverage data get overridden with that change?

**Comment by schlamar** [comment]
`data_suffix=True` should create a indistinguishable file name. But this could be the cause of our race condition: [here](https://bitbucket.org/ned/coveragepy/src/fd5363090034d14e2ea1c645248c5b6c6eb6beec/coverage/control.py?at=default#control.py-615) is the implementation.  

It's possible that `random.randint(0, 999999)` collides so we might actually overwrite data from a slave...
